name: Test and create Docker image

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: shadowJar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload .jar file
        uses: actions/upload-artifact@v3
        with:
          name: suomenlinna-ferry-hfp.jar
          path: build/libs/suomenlinna-ferry-hfp.jar
  build-develop-docker-image:
    needs: test
    runs-on: ubuntu-latest
    # Run only on develop branch
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Download .jar file
        uses: actions/download-artifact@v3
        with:
          name: suomenlinna-ferry-hfp.jar
          path: build/libs
      - name: Build and publish develop Docker image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: hsldevcom/suomenlinna-ferry-hfp
          username: ${{ secrets.TRANSITDATA_DOCKERHUB_USER }}
          password: ${{ secrets.TRANSITDATA_DOCKERHUB_TOKEN  }}
          tags: "latest"
  build-release-docker-image:
    needs: test
    runs-on: ubuntu-latest
    # Run only for tagged commits
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - name: Download .jar file
        uses: actions/download-artifact@v3
        with:
          name: suomenlinna-ferry-hfp.jar
          path: build/libs
      - name: Get Git tag name
        id: git_tag
        run: echo ::set-output name=GIT_TAG::${GITHUB_REF/refs\/tags\//}
      - name: Build and publish release Docker image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: hsldevcom/suomenlinna-ferry-hfp
          username: ${{ secrets.TRANSITDATA_DOCKERHUB_USER }}
          password: ${{ secrets.TRANSITDATA_DOCKERHUB_TOKEN  }}
          tags: "prod,${{ steps.git_tag.outputs.GIT_TAG }}"
  build-aks-dev-docker-image:
    needs: test
    runs-on: ubuntu-latest
    # Run only on aks-dev branch
    if: github.ref == 'refs/heads/aks-dev'
    steps:
      - uses: actions/checkout@v2
      - name: Download .jar file
        uses: actions/download-artifact@v3
        with:
          name: suomenlinna-ferry-hfp.jar
          path: build/libs
      - name: Build and publish aks-dev Docker image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: hsldevcom/suomenlinna-ferry-hfp
          username: ${{ secrets.TRANSITDATA_DOCKERHUB_USER }}
          password: ${{ secrets.TRANSITDATA_DOCKERHUB_TOKEN }}
          tags: aks-dev